
@startuml
hide footbox
title 基本再生シーケンス
autonumber

box "Android Activity" #LightBlue
	participant QMDXPlayerProxy
	participant QMDXPlayerReplica
end box
box "Android Server"
  participant QMDXPlayerServiceProxy
  participant QMDXPlayer
end box

QMDXPlayerProxy -> QMDXPlayerReplica
QMDXPlayerReplica->QMDXPlayerServiceProxy
QMDXPlayerServiceProxy->QMDXPlayer

@enduml
